export enum TypeCulture {
  CEREALE = 'CEREALE',

  LEGUMINEUSE = 'LEGUMINEUSE',

  TUBERCULE = 'TUBERCULE',

  FRUIT = 'FRUIT',

  LEGUME = 'LEGUME',

  OLEAGINEUX = 'OLEAGINEUX',

  PLANTE_FOURRAGERE = 'PLANTE_FOURRAGERE',
}
